// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUSaYO_nwUg2uv04MDxyg3plfKbm8RHAM',
    appId: '1:468941713540:web:9b6c981cea997c5c0a12d1',
    messagingSenderId: '468941713540',
    projectId: 'genealogyguru-es-2223',
    authDomain: 'genealogyguru-es-2223.firebaseapp.com',
    storageBucket: 'genealogyguru-es-2223.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADLXLhbdXx8w5FEVy75OZ9z-YS4SNd8lw',
    appId: '1:468941713540:android:22db31ec67681d5d0a12d1',
    messagingSenderId: '468941713540',
    projectId: 'genealogyguru-es-2223',
    storageBucket: 'genealogyguru-es-2223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-K-vE0iG1jSHCENm3XFUVondPBAY4RQ0',
    appId: '1:468941713540:ios:334aeec0bea282920a12d1',
    messagingSenderId: '468941713540',
    projectId: 'genealogyguru-es-2223',
    storageBucket: 'genealogyguru-es-2223.appspot.com',
    iosClientId: '468941713540-6a5olcpfd0ovct1j3rci776sptd4mlkf.apps.googleusercontent.com',
    iosBundleId: 'com.app.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-K-vE0iG1jSHCENm3XFUVondPBAY4RQ0',
    appId: '1:468941713540:ios:334aeec0bea282920a12d1',
    messagingSenderId: '468941713540',
    projectId: 'genealogyguru-es-2223',
    storageBucket: 'genealogyguru-es-2223.appspot.com',
    iosClientId: '468941713540-6a5olcpfd0ovct1j3rci776sptd4mlkf.apps.googleusercontent.com',
    iosBundleId: 'com.app.app',
  );
}
